### ISSUE TITLE
Add few more data in response of create comment api

### ISSUE THREAD

**Issue by errorr404** [DivyanshBatham/cb-candids-server#21]
Return this author details
![image](https://user-images.githubusercontent.com/29652551/65581362-f03c0880-df98-11e9-9f92-e3ad8cfbd4b1.png)
 **insted of**
![image](https://user-images.githubusercontent.com/29652551/65581422-0e096d80-df99-11e9-8b2c-ef446320a082.png)

in response of create comment api --> [https://calm-waters-47062.herokuapp.com/posts/{{postId}}/comments](https://calm-waters-47062.herokuapp.com/posts/{{postId}}/comments)

**Comment by DivyanshBatham** [comment]
Fixed in 117912ac07bd3bf847397db9172c5f000ac26d17
